Note:
1. The file aggregatedData.csv is the clean dataset which aggregates all blog, magazine, and wiki data.
2. In the final dataframe, there are four columns related to score: author score, data source score, like score, and comment score.
3. I did not simulate the search process. But if the words input by the user matche with the words in the most_common_words column, then one match is one score.

In [1]:
import pandas as pd
import numpy as np
import re
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
df = pd.read_csv("aggregatedData.csv",encoding = "ISO-8859-1")

In [3]:
df.head(5)

,Unnamed: 0,Article,Author,Comment,Content,Data_source,Date,Like,Most_common_words,Table of Contents,Title
0,0,NaN,Rick Beach,0.0,"by RICK BEACH, COPA?? SAFETY CHAIR\nThis unusu...",blog,12/30/2018 23:52,4.0,"['caps', 'pilot', 'accident', 'rocket', 'deplo...",How did the accident unfold?What evidence was ...,"CAPS Deployment Anomaly at Colorado Springs, C..."
1,1,NaN,Rick Beach,8.0,Every Cirrus aircraft built has a parachute sy...,blog,1/17/2016 0:50,0.0,"['caps', 'low', 'altitude', 'pull', 'attitude'...",How Low?How High?Know your Aircraft: The G5 is...,CAPS: How Low Can You Go? Or How High Do You N...
2,2,NaN,Rick Beach,2.0,(This article appears as the safety column in ...,blog,9/13/2017 23:27,1.0,"['cirrus', 'training', 'new', 'transition', 't...",Reach the Unreachable Low time-in-type vs low ...,"""Reach the Unreachable"" safety column in COPA ..."
3,3,NaN,Rick Beach,0.0,This column will appear in the Nov/Dec 2018 is...,blog,10/15/2018 4:22,12.0,"['runway', 'figure', 'left', 'airplane', 'wing...",NaN,?Â?That Sounds Expensive?Â? -- It Happened t...
4,4,NaN,Rick Beach,4.0,A Note from the Guest Editor\nThis June 2017 i...,blog,6/10/2017 18:11,0.0,"['copa', 'training', 'cirrus', 'safety', 'pilo...",A Note from the Guest Editor Success has Many ...,Guest Editor column to Special Safety Issue of...

Build table of Author: By the total number of likes he/she receved, number of work they published, time since the author joined the copa. However, we do not have the demographic data of user, so here time_with_copa is 0 for all.

In [4]:
author_table = df[['Author','Like']]
author_table_processed = author_table
author_table_processed.head(5)

       Author  Like
0  Rick Beach   4.0
1  Rick Beach   0.0
2  Rick Beach   1.0
3  Rick Beach  12.0
4  Rick Beach   0.0

In [5]:
author_list = list(df['Author'].dropna())
author_list

['Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'Rick Beach',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 'GIL WILLIAMSON',
 'KIM BLONIGEN',
 'RICK BEACH',
 'RICK BEACH',
 'JERROLD SECKLER',
 'TRIP TAYLOR',
 ' ctrease',
 ' Mark Craig',
 ' Stuart Simek',
 ' Michael Samp',
 ' John Shaeffer',
 ' Roberto Dabed',
 ' Jim Lewis',
 ' John Evans',
 ' Eharrison',
 ' Peter Storer',
 ' Peter Storer',
 ' Peter Storer',
 ' Eharrison',
 ' Eharrison',
 ' Peter Storer',
 ' Peter Storer',
 ' Peter Storer',
 ' Peter Storer',
 ' Peter Storer',
 ' Peter Storer',
 ' Peter Storer',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Stephen Upton',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Roger Whittier',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Roger Whittier',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Roger Whittier',
 ' Eharrison',
 ' John Ylinen',
 ' John Ylinen',
 ' Peter Storer',
 ' Peter Storer',
 ' Peter Storer',
 ' Eharrison',
 ' Peter Storer',
 ' Peter Storer',
 ' Eharrison',
 ' Eharrison',
 ' Peter Storer',
 ' Peter Storer',
 ' Eharrison',
 ' Peter Storer',
 ' Peter Storer',
 ' Peter Storer',
 ' Peter Storer',
 ' Peter Storer',
 ' Peter Storer',
 ' Eharrison',
 ' Peter Storer',
 ' Peter Storer',
 ' Eharrison',
 ' Alexis von Croy',
 ' Scott  Philiben',
 ' Roger Whittier',
 ' Alexis von Croy',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Peter Storer',
 ' Eharrison',
 ' Alexis von Croy',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Eharrison',
 ' Gordon Feingold',
 ' Eharrison',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Eharrison',
 ' Roger Whittier',
 ' Eharrison',
 ' Roger Whittier',
 ' Peter Storer',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Eharrison',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Steve Lucas',
 ' Peter Storer',
 ' Roger Whittier',
 ' John Ylinen',
 ' Eharrison',
 ' Roger Whittier',
 ' Eharrison',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Peter Storer',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Eharrison',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Eharrison',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Mike McCarthy',
 ' Eharrison',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Roger Whittier',
 ' Eharrison',
 ' Roger Whittier',
 ' Eharrison',
 ' Roger Whittier',
 ' Eharrison',
 ' Roger Whittier',
 ' Eharrison',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Eharrison',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Eharrison',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Eharrison',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Michael Harris',
 ' Eharrison',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Curtis Sanford',
 ' Roger Whittier',
 ' Eharrison',
 ' Roger Whittier',
 ' Eharrison',
 ' Roger Whittier',
 ' Eharrison',
 ' Roger Whittier',
 ' Steve Lucas',
 ' Steve Lucas',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Steve Lucas',
 ' Eharrison',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Eharrison',
 ' Eharrison',
 ' Roger Whittier',
 ' Chris Rose',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Eharrison',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Eharrison',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' William Dillon',
 ' Eharrison',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Eharrison',
 ' Roger Whittier',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Roger Whittier',
 ' Eharrison',
 ' Roger Whittier',
 ' Eharrison',
 ' Eharrison',
 ' Eharrison',
 ' Roger Whittier',
 ' Eharrison',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' Roger Whittier',
 ' John Ylinen',
 ' Eharrison',
 ' Eharrison']

In [6]:
author_table_processed = author_table_processed[author_table_processed['Author'].isin(author_list)]
author_table_processed

              Author  Like
0         Rick Beach   4.0
1         Rick Beach   0.0
2         Rick Beach   1.0
3         Rick Beach  12.0
4         Rick Beach   0.0
5         Rick Beach   0.0
6         Rick Beach   4.0
7         Rick Beach   1.0
8         Rick Beach   0.0
9         Rick Beach   3.0
10        Rick Beach   0.0
11        Rick Beach   2.0
12        Rick Beach   3.0
13        Rick Beach   0.0
14        Rick Beach   4.0
15        Rick Beach   3.0
16        Rick Beach   0.0
17        Rick Beach   0.0
18        Rick Beach   0.0
19        Rick Beach   0.0
20        Rick Beach   0.0
21        Rick Beach   0.0
22        Rick Beach   0.0
23        Rick Beach   0.0
24        Rick Beach   0.0
25        Rick Beach   0.0
26        Rick Beach   0.0
27        Rick Beach   0.0
28        Rick Beach   0.0
29        Rick Beach   0.0
..               ...   ...
733        Eharrison   NaN
734        Eharrison   NaN
735        Eharrison   NaN
736        Eharrison   NaN
737        Eharrison   NaN
738        Eharrison   NaN
739   Roger Whittier   NaN
740   Roger Whittier   NaN
741   Roger Whittier   NaN
742        Eharrison   NaN
743        Eharrison   NaN
744        Eharrison   NaN
745   Roger Whittier   NaN
746        Eharrison   NaN
747   Roger Whittier   NaN
748        Eharrison   NaN
749        Eharrison   NaN
750        Eharrison   NaN
751   Roger Whittier   NaN
752        Eharrison   NaN
753   Roger Whittier   NaN
754   Roger Whittier   NaN
755   Roger Whittier   NaN
756   Roger Whittier   NaN
757   Roger Whittier   NaN
758   Roger Whittier   NaN
759   Roger Whittier   NaN
760      John Ylinen   NaN
761        Eharrison   NaN
762        Eharrison   NaN

[527 rows x 2 columns]

In [7]:
#For the same author, there are different representations of his/her name in different source. So transfer them all to lower case.
for i in range(len(author_table)):
    if (type(author_table['Author'][i])==str):
        author_table_processed['Author'][i] = author_table['Author'][i].lower()
author_table_processed.head(5)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  exec(code_obj, self.user_global_ns, self.user_ns)

       Author  Like
0  rick beach   4.0
1  rick beach   0.0
2  rick beach   1.0
3  rick beach  12.0
4  rick beach   0.0

In [8]:
A = author_table_processed['Author'].unique()
AA = {'Author':list(A)}
AA = pd.DataFrame(AA)
A = list(AA['Author'].dropna())
len(A) #Except NaN, there are 27 authors in total.

27

In [9]:
author = pd.DataFrame({'Author':A})
author['num_of_work'] = 0
author['num_of_like'] = 0
author['time_with_copa'] = 0

In [10]:
#Count the number of work for each author.
for i in range(len(A)):
    author['num_of_work'][i] = list(author_table_processed['Author']).count(A[i])

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [11]:
#Count the number of like for each author.
for i in range(len(A)):
    author1 = author_table_processed.loc[author_table_processed['Author']==A[i]]
    author1 = author1.dropna()
    total_like = sum(author1['Like'])
    author['num_of_like'][i] = sum(author1['Like'])

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [12]:
author = author.fillna(0) #Since all columns are scores, so fill the NaN with 0.

In [13]:
total_num_of_work = sum(author['num_of_work'])
total_num_of_like = sum(author['num_of_like'])

In [14]:
author

              Author  num_of_work  num_of_like  time_with_copa
0         rick beach           90           37               0
1     gil williamson           30            0               0
2       kim blonigen           30            0               0
3    jerrold seckler           30            0               0
4        trip taylor           30            0               0
5            ctrease            1            0               0
6         mark craig            1            0               0
7       stuart simek            1            0               0
8       michael samp            1            0               0
9      john shaeffer            1            0               0
10     roberto dabed            1            0               0
11         jim lewis            1            0               0
12        john evans            1            0               0
13         eharrison          138            0               0
14      peter storer           29            0               0
15     stephen upton            1            0               0
16    roger whittier          123            0               0
17       john ylinen            4            0               0
18   alexis von croy            3            0               0
19   scott  philiben            1            0               0
20   gordon feingold            1            0               0
21       steve lucas            4            0               0
22     mike mccarthy            1            0               0
23    michael harris            1            0               0
24    curtis sanford            1            0               0
25        chris rose            1            0               0
26    william dillon            1            0               0

In [15]:
#Calculate score for number of work
score_num_of_work =list()
for i in range(len(A)):
    score_num_of_work.append(author['num_of_work'][i]/total_num_of_work)
author = pd.concat([author, pd.DataFrame(score_num_of_work)], axis=1)
author.columns =['Author','num_of_work','num_of_like','time_with_copa','score_num_of_work']
author

,Author,num_of_work,num_of_like,time_with_copa,score_num_of_work
0,rick beach,90,37,0,0.170778
1,gil williamson,30,0,0,0.056926
2,kim blonigen,30,0,0,0.056926
3,jerrold seckler,30,0,0,0.056926
4,trip taylor,30,0,0,0.056926
5,ctrease,1,0,0,0.001898
6,mark craig,1,0,0,0.001898
7,stuart simek,1,0,0,0.001898
8,michael samp,1,0,0,0.001898
9,john shaeffer,1,0,0,0.001898
10,roberto dabed,1,0,0,0.001898
11,jim lewis,1,0,0,0.001898
12,john evans,1,0,0,0.001898
13,eharrison,138,0,0,0.261860
14,peter storer,29,0,0,0.055028
15,stephen upton,1,0,0,0.001898
16,roger whittier,123,0,0,0.233397
17,john ylinen,4,0,0,0.007590
18,alexis von croy,3,0,0,0.005693
19,scott philiben,1,0,0,0.001898
20,gordon feingold,1,0,0,0.001898
21,steve lucas,4,0,0,0.007590
22,mike mccarthy,1,0,0,0.001898
23,michael harris,1,0,0,0.001898
24,curtis sanford,1,0,0,0.001898
25,chris rose,1,0,0,0.001898
26,william dillon,1,0,0,0.001898

In [16]:
#Calculate score for number of like
score_num_of_like =list()
for i in range(len(A)):
    score_num_of_like.append(author['num_of_like'][i]/total_num_of_like)
author = pd.concat([author, pd.DataFrame(score_num_of_like)], axis=1)
author.columns =['Author','num_of_work','num_of_like','time_with_copa','score_num_of_work','score_num_of_like']
author

,Author,num_of_work,num_of_like,time_with_copa,score_num_of_work,score_num_of_like
0,rick beach,90,37,0,0.170778,1.0
1,gil williamson,30,0,0,0.056926,0.0
2,kim blonigen,30,0,0,0.056926,0.0
3,jerrold seckler,30,0,0,0.056926,0.0
4,trip taylor,30,0,0,0.056926,0.0
5,ctrease,1,0,0,0.001898,0.0
6,mark craig,1,0,0,0.001898,0.0
7,stuart simek,1,0,0,0.001898,0.0
8,michael samp,1,0,0,0.001898,0.0
9,john shaeffer,1,0,0,0.001898,0.0
10,roberto dabed,1,0,0,0.001898,0.0
11,jim lewis,1,0,0,0.001898,0.0
12,john evans,1,0,0,0.001898,0.0
13,eharrison,138,0,0,0.261860,0.0
14,peter storer,29,0,0,0.055028,0.0
15,stephen upton,1,0,0,0.001898,0.0
16,roger whittier,123,0,0,0.233397,0.0
17,john ylinen,4,0,0,0.007590,0.0
18,alexis von croy,3,0,0,0.005693,0.0
19,scott philiben,1,0,0,0.001898,0.0
20,gordon feingold,1,0,0,0.001898,0.0
21,steve lucas,4,0,0,0.007590,0.0
22,mike mccarthy,1,0,0,0.001898,0.0
23,michael harris,1,0,0,0.001898,0.0
24,curtis sanford,1,0,0,0.001898,0.0
25,chris rose,1,0,0,0.001898,0.0
26,william dillon,1,0,0,0.001898,0.0

In [17]:
#Calculate total score for each author. Put more weight on num_of_like and num_of_work.
score = [score_num_of_work[i]*2 + score_num_of_like[i]*3 for i in range(len(score_num_of_work))] 
author = pd.concat([author, pd.DataFrame(score)], axis=1)
author.columns =['Author','num_of_work','num_of_like','time_with_copa','score_num_of_work','score_num_of_like','score']
author

,Author,num_of_work,num_of_like,time_with_copa,score_num_of_work,score_num_of_like,score
0,rick beach,90,37,0,0.170778,1.0,3.341556
1,gil williamson,30,0,0,0.056926,0.0,0.113852
2,kim blonigen,30,0,0,0.056926,0.0,0.113852
3,jerrold seckler,30,0,0,0.056926,0.0,0.113852
4,trip taylor,30,0,0,0.056926,0.0,0.113852
5,ctrease,1,0,0,0.001898,0.0,0.003795
6,mark craig,1,0,0,0.001898,0.0,0.003795
7,stuart simek,1,0,0,0.001898,0.0,0.003795
8,michael samp,1,0,0,0.001898,0.0,0.003795
9,john shaeffer,1,0,0,0.001898,0.0,0.003795
10,roberto dabed,1,0,0,0.001898,0.0,0.003795
11,jim lewis,1,0,0,0.001898,0.0,0.003795
12,john evans,1,0,0,0.001898,0.0,0.003795
13,eharrison,138,0,0,0.261860,0.0,0.523719
14,peter storer,29,0,0,0.055028,0.0,0.110057
15,stephen upton,1,0,0,0.001898,0.0,0.003795
16,roger whittier,123,0,0,0.233397,0.0,0.466793
17,john ylinen,4,0,0,0.007590,0.0,0.015180
18,alexis von croy,3,0,0,0.005693,0.0,0.011385
19,scott philiben,1,0,0,0.001898,0.0,0.003795
20,gordon feingold,1,0,0,0.001898,0.0,0.003795
21,steve lucas,4,0,0,0.007590,0.0,0.015180
22,mike mccarthy,1,0,0,0.001898,0.0,0.003795
23,michael harris,1,0,0,0.001898,0.0,0.003795
24,curtis sanford,1,0,0,0.001898,0.0,0.003795
25,chris rose,1,0,0,0.001898,0.0,0.003795
26,william dillon,1,0,0,0.001898,0.0,0.003795

In [18]:
author

,Author,num_of_work,num_of_like,time_with_copa,score_num_of_work,score_num_of_like,score
0,rick beach,90,37,0,0.170778,1.0,3.341556
1,gil williamson,30,0,0,0.056926,0.0,0.113852
2,kim blonigen,30,0,0,0.056926,0.0,0.113852
3,jerrold seckler,30,0,0,0.056926,0.0,0.113852
4,trip taylor,30,0,0,0.056926,0.0,0.113852
5,ctrease,1,0,0,0.001898,0.0,0.003795
6,mark craig,1,0,0,0.001898,0.0,0.003795
7,stuart simek,1,0,0,0.001898,0.0,0.003795
8,michael samp,1,0,0,0.001898,0.0,0.003795
9,john shaeffer,1,0,0,0.001898,0.0,0.003795
10,roberto dabed,1,0,0,0.001898,0.0,0.003795
11,jim lewis,1,0,0,0.001898,0.0,0.003795
12,john evans,1,0,0,0.001898,0.0,0.003795
13,eharrison,138,0,0,0.261860,0.0,0.523719
14,peter storer,29,0,0,0.055028,0.0,0.110057
15,stephen upton,1,0,0,0.001898,0.0,0.003795
16,roger whittier,123,0,0,0.233397,0.0,0.466793
17,john ylinen,4,0,0,0.007590,0.0,0.015180
18,alexis von croy,3,0,0,0.005693,0.0,0.011385
19,scott philiben,1,0,0,0.001898,0.0,0.003795
20,gordon feingold,1,0,0,0.001898,0.0,0.003795
21,steve lucas,4,0,0,0.007590,0.0,0.015180
22,mike mccarthy,1,0,0,0.001898,0.0,0.003795
23,michael harris,1,0,0,0.001898,0.0,0.003795
24,curtis sanford,1,0,0,0.001898,0.0,0.003795
25,chris rose,1,0,0,0.001898,0.0,0.003795
26,william dillon,1,0,0,0.001898,0.0,0.003795

In [19]:
#Sort the author by score
author.sort_values("score",inplace=True)

In [20]:
#Tag each author with its rank. The author with highest score is with highest rank
author.reset_index(drop=True,inplace=True)
author['rank'] = 0
for i in range(len(author)):
    author['rank'][i] = i+1

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [21]:
author

,Author,num_of_work,num_of_like,time_with_copa,score_num_of_work,score_num_of_like,score,rank
0,william dillon,1,0,0,0.001898,0.0,0.003795,1
1,mike mccarthy,1,0,0,0.001898,0.0,0.003795,2
2,gordon feingold,1,0,0,0.001898,0.0,0.003795,3
3,scott philiben,1,0,0,0.001898,0.0,0.003795,4
4,stephen upton,1,0,0,0.001898,0.0,0.003795,5
5,chris rose,1,0,0,0.001898,0.0,0.003795,6
6,michael harris,1,0,0,0.001898,0.0,0.003795,7
7,jim lewis,1,0,0,0.001898,0.0,0.003795,8
8,roberto dabed,1,0,0,0.001898,0.0,0.003795,9
9,john evans,1,0,0,0.001898,0.0,0.003795,10
10,michael samp,1,0,0,0.001898,0.0,0.003795,11
11,stuart simek,1,0,0,0.001898,0.0,0.003795,12
12,mark craig,1,0,0,0.001898,0.0,0.003795,13
13,ctrease,1,0,0,0.001898,0.0,0.003795,14
14,john shaeffer,1,0,0,0.001898,0.0,0.003795,15
15,curtis sanford,1,0,0,0.001898,0.0,0.003795,16
16,alexis von croy,3,0,0,0.005693,0.0,0.011385,17
17,john ylinen,4,0,0,0.007590,0.0,0.015180,18
18,steve lucas,4,0,0,0.007590,0.0,0.015180,19
19,peter storer,29,0,0,0.055028,0.0,0.110057,20
20,trip taylor,30,0,0,0.056926,0.0,0.113852,21
21,jerrold seckler,30,0,0,0.056926,0.0,0.113852,22
22,kim blonigen,30,0,0,0.056926,0.0,0.113852,23
23,gil williamson,30,0,0,0.056926,0.0,0.113852,24
24,roger whittier,123,0,0,0.233397,0.0,0.466793,25
25,eharrison,138,0,0,0.261860,0.0,0.523719,26
26,rick beach,90,37,0,0.170778,1.0,3.341556,27

In [22]:
author_rank = author[['Author','rank']]
author_rank.columns = ['Author','author_score']
author_rank #Milestone1:obtain all authors and their ranks as their final score

              Author  author_score
0     william dillon             1
1      mike mccarthy             2
2    gordon feingold             3
3    scott  philiben             4
4      stephen upton             5
5         chris rose             6
6     michael harris             7
7          jim lewis             8
8      roberto dabed             9
9         john evans            10
10      michael samp            11
11      stuart simek            12
12        mark craig            13
13           ctrease            14
14     john shaeffer            15
15    curtis sanford            16
16   alexis von croy            17
17       john ylinen            18
18       steve lucas            19
19      peter storer            20
20       trip taylor            21
21   jerrold seckler            22
22      kim blonigen            23
23    gil williamson            24
24    roger whittier            25
25         eharrison            26
26        rick beach            27

In [23]:
df1 = df
for i in range(len(df)):
    if (type(df['Author'][i])==str):
        df1['Author'][i] = df['Author'][i].lower()
        
result = pd.merge(df1, author_rank, how='left', on=['Author'])

for i in range(len(result)):
    if (np.isnan(result['author_score'][i])):
        result['author_score'][i] = 0

result.head(100) #Milestone2: match all authors in the df with their score.

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

,Unnamed: 0,Article,Author,Comment,Content,Data_source,Date,Like,Most_common_words,Table of Contents,Title,author_score
0,0,NaN,rick beach,0.0,"by RICK BEACH, COPA?? SAFETY CHAIR\nThis unusu...",blog,12/30/2018 23:52,4.0,"['caps', 'pilot', 'accident', 'rocket', 'deplo...",How did the accident unfold?What evidence was ...,"CAPS Deployment Anomaly at Colorado Springs, C...",27.0
1,1,NaN,rick beach,8.0,Every Cirrus aircraft built has a parachute sy...,blog,1/17/2016 0:50,0.0,"['caps', 'low', 'altitude', 'pull', 'attitude'...",How Low?How High?Know your Aircraft: The G5 is...,CAPS: How Low Can You Go? Or How High Do You N...,27.0
2,2,NaN,rick beach,2.0,(This article appears as the safety column in ...,blog,9/13/2017 23:27,1.0,"['cirrus', 'training', 'new', 'transition', 't...",Reach the Unreachable Low time-in-type vs low ...,"""Reach the Unreachable"" safety column in COPA ...",27.0
3,3,NaN,rick beach,0.0,This column will appear in the Nov/Dec 2018 is...,blog,10/15/2018 4:22,12.0,"['runway', 'figure', 'left', 'airplane', 'wing...",NaN,?Â?That Sounds Expensive?Â? -- It Happened t...,27.0
4,4,NaN,rick beach,4.0,A Note from the Guest Editor\nThis June 2017 i...,blog,6/10/2017 18:11,0.0,"['copa', 'training', 'cirrus', 'safety', 'pilo...",A Note from the Guest Editor Success has Many ...,Guest Editor column to Special Safety Issue of...,27.0
5,5,NaN,rick beach,0.0,CaresCritical Incident Response ProgramCIRP i...,blog,8/27/2019 23:15,0.0,"['cirp', 'copa', 'community', 'peer', 'support...",Critical Incident Response for the COPA Commun...,Critical Incident Response for the COPA Community,27.0
6,6,NaN,rick beach,5.0,"For??years,??safety??advocates??have??preached...",blog,1/17/2016 0:51,4.0,"['loss', 'control', 'accidents', 'flight', 'ci...",Cirrus Aircraft Studied Loss of ControlAnalysi...,COPA/Cirrus Aircraft Examine Loss of Control A...,27.0
7,7,NaN,rick beach,0.0,Having participated in several annual meetings...,blog,12/1/2015 18:52,1.0,"['ntsb', 'type', 'investigation', 'investigati...",NaN,Ways that Aviation Type Clubs can prepare and ...,27.0
8,8,NaN,rick beach,2.0,Compare the past six months\r\nwith the same t...,blog,12/8/2012 11:03,0.0,"['caps', 'accidents', 'year', '2012', 'copa', ...",NaN,"In Last Six Months, Half the Fatal Accidents a...",27.0
9,9,NaN,rick beach,5.0,In a recent discussion of the survivable CAPS ...,blog,11/30/2014 18:26,3.0,"['engine', 'fuel', 'oil', 'caps', 'power', 'co...",Recent Fatal Accidents BAD WEATHER FLYINGPILOT...,Turning Fatals into CAPS Saves and Avoiding CA...,27.0
10,10,NaN,rick beach,2.0,(updated with additional Probable Cause determ...,blog,11/24/2014 19:47,0.0,"['engine', 'loss', 'power', 'io', 'sr22', '550...",NaN,Reviewing the causes of loss of engine power i...,27.0
11,11,NaN,rick beach,2.0,"During the COPA dinner at Oshkosh 2014, a brie...",blog,8/21/2014 20:49,2.0,"['cirrus', 'accidents', 'fatal', 'aircraft', '...",NaN,Safety Good News presentation at COPA Dinner @...,27.0
12,12,NaN,rick beach,3.0,"Since the beginning of 2014, Cirrus accident r...",blog,7/1/2014 17:02,3.0,"['cirrus', 'accidents', 'fatal', 'flying', 'fl...",Fatalities in Cirrus AccidentsFatal Cirrus Acc...,Mid-Year 2014 Update on Improved Cirrus accide...,27.0
13,13,NaN,rick beach,0.0,"Recently, a forum discussion on BeechTalk posi...",blog,6/18/2014 20:52,0.0,"['pilot', 'caps', 'water', 'landed', 'engine',...",NaN,On CAPS deployments that landed in water -- ab...,27.0
14,14,NaN,rick beach,8.0,"Recently, a private conversation with a COPA m...",blog,6/18/2014 21:33,4.0,"['injuries', 'caps', 'fracture', 'lower', 'par...",NaN,On injuries from surviving a CAPS pull,27.0
15,15,NaN,rick beach,9.0,The Cirrus Owners and Pilots Association (COPA...,blog,4/1/2014 20:44,3.0,"['accidents', 'number', 'cirrus', 'fatal', 'ca...",Cirrus Fatal AccidentsFatalities in Cirrus Fat...,Cirrus accident history continues improvement ...,27.0
16,16,NaN,rick beach,2.0,As COPA members may know from frequenting the ...,blog,3/31/2014 19:08,0.0,"['accidents', 'maneuvering', 'cirrus', 'fatal'...",NTSB data on maneuvering in fatal accidentsMor...,About Maneuvering in Fatal Cirrus Accidents,27.0
17,17,NaN,rick beach,0.0,"A story from EAA,??Experimental Fatal Accident...",blog,10/20/2013 21:09,0.0,"['cirrus', 'fatal', 'accidents', 'aircraft', '...",NaN,Cirrus fatal accidents drop more than GA or Am...,27.0
18,18,NaN,rick beach,1.0,"In December of 2005, the first post with the p...",blog,8/14/2013 17:46,0.0,"['caps', 'pull', 'altitude', 'early', 'control...",NaN,"Another exposition on the mantra Pull Early, P...",27.0
19,19,NaN,rick beach,0.0,"Quite often after an accident in a Cirrus, avi...",blog,7/20/2013 13:08,0.0,"['cirrus', 'experience', 'pilots', 'time', 'ac...",NaN,Update on pilot experience in Cirrus fatal acc...,27.0
20,20,NaN,rick beach,0.0,The Cirrus community reached a significant saf...,blog,7/11/2013 16:46,0.0,"['accidents', 'caps', 'fatal', 'cirrus', 'save...",NaN,Cirrus Safety Milestone: Equal number of CAPS ...,27.0
21,21,NaN,rick beach,0.0,What do we learn from recorded data in our Cir...,blog,6/16/2013 23:56,0.0,"['data', 'flight', 'cirrus', 'files', 'acciden...",NaN,Recorded flight data helps us fly more safely,27.0
22,22,NaN,rick beach,0.0,"Recently, two things coincided to bracket the ...",blog,5/25/2013 18:34,0.0,"['cirrus', 'safety', 'pilots', 'better', 'caps...",NaN,Another discussion of the Cirrus safety record,27.0
23,23,NaN,rick beach,1.0,"Today, I was invited to submit comments on a f...",blog,4/4/2013 2:14,0.0,"['accident', 'ntsb', 'factual', 'copa', 'safet...",NaN,Letter to NTSB concerning early access to fact...,27.0
24,24,NaN,rick beach,0.0,COPA\r\nSafety: Pull Often!\nby Rick Beach\n??...,blog,3/13/2013 22:29,0.0,"['plane', 'parachute', 'caps', 'copa', 'bob', ...",NaN,COPA Safety: Pull Often! (from COPA Pilot maga...,27.0
25,25,NaN,rick beach,2.0,"In the past few months, COPA has worked with C...",blog,12/9/2012 0:07,0.0,"['time', 'aircraft', 'cirrus', 'hours', 'data'...",NaN,Recalibrating the flying hours for the Cirrus ...,27.0
26,26,NaN,rick beach,2.0,Compare the past six months\r\nwith the same t...,blog,12/8/2012 11:03,0.0,"['caps', 'accidents', 'year', '2012', 'copa', ...",NaN,"In Last Six Months, Half the Fatal Accidents a...",27.0
27,27,NaN,rick beach,0.0,"In the accident history of Cirrus accidents, w...",blog,11/22/2012 19:25,0.0,"['caps', 'parachute', 'impact', 'ground', 'act...",NaN,Refining what we call a CAPS Save,27.0
28,28,NaN,rick beach,2.0,"In the thread, Cirrus fatal #89 in SR20 N764RV...",blog,7/16/2012 16:48,0.0,"['dissonance', 'cognitive', 'vfr', 'clouds', '...",NaN,On cognitive dissonance in flying,27.0
29,29,NaN,rick beach,1.0,Dr. Richard ?Â?Dick?Â? McGlaughlin and his d...,blog,1/10/2012 6:34,0.0,"['parachute', 'dick', 'plane', 'cirrus', 'wate...",NaN,Early Reflections on CAPS Pull #32 by Dick McG...,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...
70,40,Service Center Spotlight,NaN,NaN,FAR WESTERN STATESCALIFORNIA American Aircraft...,magazine,NaN,NaN,"['aviation', 'pg', 'air', 'aircraft', 'aero', ...",NaN,NaN,0.0
71,41,Advertising Index,NaN,NaN,NEW YORK Boshart Enterprises Aircraft Services...,magazine,NaN,NaN,"['aviation', 'air', 'aircraft', 'pg', 'service...",NaN,NaN,0.0
72,42,President's Column,NaN,NaN,APRIL 20194 COPA PilotCOPA has the incredible ...,magazine,NaN,NaN,"['copa', 'com', 'members', 'event', 'pilot', '...",NaN,NaN,0.0
73,43,COPA News,NaN,NaN,APRIL 20196 COPA PilotSmall WorldAbout two yea...,magazine,NaN,NaN,"['copa', 'migration', 'new', 'cirrus', 'orlean...",NaN,NaN,0.0
74,44,Regional News,gil williamson,NaN,APRIL 201912 COPA PilotCOPA Pilot Can you give...,magazine,NaN,NaN,"['copa', 'pilot', 'plane', 'pilots', 'cirrus',...",NaN,NaN,24.0
75,45,Cirrus Perspective,NaN,NaN,APRIL 201918 COPA PilotI am also working on ex...,magazine,NaN,NaN,"['copa', 'foundation', 'pilot', 'board', 'memb...",NaN,NaN,0.0
76,46,Member Spotlight,kim blonigen,NaN,APRIL 201922 COPA PilotRegional and Internatio...,magazine,NaN,NaN,"['copa', 'events', 'international', 'migration...",NaN,NaN,23.0
77,47,Fly Africa ... Part Two,NaN,NaN,APRIL 201930 COPA PilotAIRCRAFT SALES PURCHASE...,magazine,NaN,NaN,"['copa', 'cirrus', 'year', 'pilot', 'csip', 'a...",NaN,NaN,0.0
78,48,Safety Talk,rick beach,NaN,APRIL 201940 COPA PilotVolume 14 Number 3COPA ...,magazine,NaN,NaN,"['copa', 'c2a', 'formation', 'pilot', 'pilots'...",NaN,NaN,27.0
79,49,Safety Feature,rick beach,NaN,APRIL 201944 COPA PilotElectronic Ignition sys...,magazine,NaN,NaN,"['engine', 'magneto', 'aircraft', 'electroair'...",NaN,NaN,27.0
80,50,Medical Musings,jerrold seckler,NaN,APRIL 201952 COPA Pilotnatural transition. Tho...,magazine,NaN,NaN,"['mission', 'pilot', 'lighthawk', 'make', 'new...",NaN,NaN,22.0
81,51,Training,trip taylor,NaN,APRIL 201954 COPA PilotI do if ll in the blank...,magazine,NaN,NaN,"['centerline', 'landing', 'pilot', 'pilots', '...",NaN,NaN,21.0
82,52,COPA Technical,NaN,NaN,APRIL 201958 COPA Pilotpilots tend to end up l...,magazine,NaN,NaN,"['aviation', 'aircraft', 'ad', 'pg', 'center',...",NaN,NaN,0.0
83,53,Directory of Authorized Service Centers,NaN,NaN,CIRRUS AUTHORIZED SERVICE CENTERSCIRRUS AUTHOR...,magazine,NaN,NaN,"['aviation', 'air', 'maintenance', 'service', ...",NaN,NaN,0.0
84,54,Service Center Spotlight,NaN,NaN,APRIL 201962 COPA PilotCIRRUS SERVICE CENTER S...,magazine,NaN,NaN,"['copa', 'join', '2830', '89130read', 'airplan...",NaN,NaN,0.0
85,55,Advertising Index,NaN,NaN,Volume 14 Number 3COPA Pilot 63Volume 14 Numbe...,magazine,NaN,NaN,"['14', '3copa', 'number', 'pilot', '63volume',...",NaN,NaN,0.0
86,56,President's Column,NaN,NaN,JULY AUGUST 20194 COPA PilotIts fullon summer ...,magazine,NaN,NaN,"['copa', 'members', 'com', 'event', 'great', '...",NaN,NaN,0.0
87,57,COPA News,NaN,NaN,JULY AUGUST 20196 COPA PilotREGIONALINTERNATIO...,magazine,NaN,NaN,"['trip', 'ight', 'copa', 'maya', 'adventure', ...",NaN,NaN,0.0
88,58,Regional News,gil williamson,NaN,JULY AUGUST 201912 COPA Pilothelped us tie dow...,magazine,NaN,NaN,"['copa', 'great', 'cirrus', 'mayan', 'campeche...",NaN,NaN,24.0
89,59,Cirrus Perspective,NaN,NaN,JULY AUGUST 201918 COPA Pilotexecutive ofcer C...,magazine,NaN,NaN,"['copa', 'pilot', 'brazil', 'cirrus', 'lohmann...",NaN,NaN,0.0
90,60,Member Spotlight,kim blonigen,NaN,JULY AUGUST 201922 COPA Pilottopics discussed ...,magazine,NaN,NaN,"['aircraft', 'copa', 'brazil', 'atc', 'policy'...",NaN,NaN,23.0
91,61,Fly Africa ... Part Two,NaN,NaN,JULY AUGUST 201930 COPA PilotHowever insurers ...,magazine,NaN,NaN,"['aircraft', 'insurance', 'coverage', 'damage'...",NaN,NaN,0.0
92,62,Safety Talk,rick beach,NaN,JULY AUGUST 201940 COPA Pilotcoastline where y...,magazine,NaN,NaN,"['mdi', 'bar', 'harbor', 'rst', 'park', 'acadi...",NaN,NaN,27.0
93,63,Safety Feature,rick beach,NaN,JULY AUGUST 201944 COPA Pilotcrossing the beac...,magazine,NaN,NaN,"['weather', 'cirrus', 'conditions', 'vfr', 'pi...",NaN,NaN,27.0
94,64,Medical Musings,jerrold seckler,NaN,JULY AUGUST 201952 COPA PilotFly with more ter...,magazine,NaN,NaN,"['weather', 'know', 'time', 'avoid', 'caps', '...",NaN,NaN,22.0
95,65,Training,trip taylor,NaN,JULY AUGUST 201954 COPA PilotSummer is here an...,magazine,NaN,NaN,"['night', 'guy', 'landings', 'currency', 'airc...",NaN,NaN,21.0
96,66,COPA Technical,NaN,NaN,JULY AUGUST 201958 COPA PilotThe ITGCKMBPC Int...,magazine,NaN,NaN,"['approach', 'cirrus', 'guy', 'landing', 'knot...",NaN,NaN,0.0
97,67,Directory of Authorized Service Centers,NaN,NaN,Volume 14 Number 6COPA Pilot 61Volume 14 Numbe...,magazine,NaN,NaN,"['14', '6copa', 'number', 'pilot', '61volume',...",NaN,NaN,0.0
98,68,Service Center Spotlight,NaN,NaN,JULY AUGUST 201962 COPA Pilotto maintain cours...,magazine,NaN,NaN,"['approach', 'cirrus', 'aircraft', 'pilots', '...",NaN,NaN,0.0
99,69,Advertising Index,NaN,NaN,Volume 14 Number 6COPA Pilot 635 percent incre...,magazine,NaN,NaN,"['aircraft', 'approach', 'pilots', 'pilot', 'a...",NaN,NaN,0.0

In [24]:
result['datasource_score'] = 0

In [25]:
#For data source, give magazine 3 points, wikis and blogs are all 1 points.
result.loc[result['Data_source']=='magazine','datasource_score']=3
result.loc[result['Data_source']=='wikis','datasource_score']=1
result.loc[result['Data_source']=='blog','datasource_score']=1

In [26]:
result.head(100)

,Unnamed: 0,Article,Author,Comment,Content,Data_source,Date,Like,Most_common_words,Table of Contents,Title,author_score,datasource_score
0,0,NaN,rick beach,0.0,"by RICK BEACH, COPA?? SAFETY CHAIR\nThis unusu...",blog,12/30/2018 23:52,4.0,"['caps', 'pilot', 'accident', 'rocket', 'deplo...",How did the accident unfold?What evidence was ...,"CAPS Deployment Anomaly at Colorado Springs, C...",27.0,1
1,1,NaN,rick beach,8.0,Every Cirrus aircraft built has a parachute sy...,blog,1/17/2016 0:50,0.0,"['caps', 'low', 'altitude', 'pull', 'attitude'...",How Low?How High?Know your Aircraft: The G5 is...,CAPS: How Low Can You Go? Or How High Do You N...,27.0,1
2,2,NaN,rick beach,2.0,(This article appears as the safety column in ...,blog,9/13/2017 23:27,1.0,"['cirrus', 'training', 'new', 'transition', 't...",Reach the Unreachable Low time-in-type vs low ...,"""Reach the Unreachable"" safety column in COPA ...",27.0,1
3,3,NaN,rick beach,0.0,This column will appear in the Nov/Dec 2018 is...,blog,10/15/2018 4:22,12.0,"['runway', 'figure', 'left', 'airplane', 'wing...",NaN,?Â?That Sounds Expensive?Â? -- It Happened t...,27.0,1
4,4,NaN,rick beach,4.0,A Note from the Guest Editor\nThis June 2017 i...,blog,6/10/2017 18:11,0.0,"['copa', 'training', 'cirrus', 'safety', 'pilo...",A Note from the Guest Editor Success has Many ...,Guest Editor column to Special Safety Issue of...,27.0,1
5,5,NaN,rick beach,0.0,CaresCritical Incident Response ProgramCIRP i...,blog,8/27/2019 23:15,0.0,"['cirp', 'copa', 'community', 'peer', 'support...",Critical Incident Response for the COPA Commun...,Critical Incident Response for the COPA Community,27.0,1
6,6,NaN,rick beach,5.0,"For??years,??safety??advocates??have??preached...",blog,1/17/2016 0:51,4.0,"['loss', 'control', 'accidents', 'flight', 'ci...",Cirrus Aircraft Studied Loss of ControlAnalysi...,COPA/Cirrus Aircraft Examine Loss of Control A...,27.0,1
7,7,NaN,rick beach,0.0,Having participated in several annual meetings...,blog,12/1/2015 18:52,1.0,"['ntsb', 'type', 'investigation', 'investigati...",NaN,Ways that Aviation Type Clubs can prepare and ...,27.0,1
8,8,NaN,rick beach,2.0,Compare the past six months\r\nwith the same t...,blog,12/8/2012 11:03,0.0,"['caps', 'accidents', 'year', '2012', 'copa', ...",NaN,"In Last Six Months, Half the Fatal Accidents a...",27.0,1
9,9,NaN,rick beach,5.0,In a recent discussion of the survivable CAPS ...,blog,11/30/2014 18:26,3.0,"['engine', 'fuel', 'oil', 'caps', 'power', 'co...",Recent Fatal Accidents BAD WEATHER FLYINGPILOT...,Turning Fatals into CAPS Saves and Avoiding CA...,27.0,1
10,10,NaN,rick beach,2.0,(updated with additional Probable Cause determ...,blog,11/24/2014 19:47,0.0,"['engine', 'loss', 'power', 'io', 'sr22', '550...",NaN,Reviewing the causes of loss of engine power i...,27.0,1
11,11,NaN,rick beach,2.0,"During the COPA dinner at Oshkosh 2014, a brie...",blog,8/21/2014 20:49,2.0,"['cirrus', 'accidents', 'fatal', 'aircraft', '...",NaN,Safety Good News presentation at COPA Dinner @...,27.0,1
12,12,NaN,rick beach,3.0,"Since the beginning of 2014, Cirrus accident r...",blog,7/1/2014 17:02,3.0,"['cirrus', 'accidents', 'fatal', 'flying', 'fl...",Fatalities in Cirrus AccidentsFatal Cirrus Acc...,Mid-Year 2014 Update on Improved Cirrus accide...,27.0,1
13,13,NaN,rick beach,0.0,"Recently, a forum discussion on BeechTalk posi...",blog,6/18/2014 20:52,0.0,"['pilot', 'caps', 'water', 'landed', 'engine',...",NaN,On CAPS deployments that landed in water -- ab...,27.0,1
14,14,NaN,rick beach,8.0,"Recently, a private conversation with a COPA m...",blog,6/18/2014 21:33,4.0,"['injuries', 'caps', 'fracture', 'lower', 'par...",NaN,On injuries from surviving a CAPS pull,27.0,1
15,15,NaN,rick beach,9.0,The Cirrus Owners and Pilots Association (COPA...,blog,4/1/2014 20:44,3.0,"['accidents', 'number', 'cirrus', 'fatal', 'ca...",Cirrus Fatal AccidentsFatalities in Cirrus Fat...,Cirrus accident history continues improvement ...,27.0,1
16,16,NaN,rick beach,2.0,As COPA members may know from frequenting the ...,blog,3/31/2014 19:08,0.0,"['accidents', 'maneuvering', 'cirrus', 'fatal'...",NTSB data on maneuvering in fatal accidentsMor...,About Maneuvering in Fatal Cirrus Accidents,27.0,1
17,17,NaN,rick beach,0.0,"A story from EAA,??Experimental Fatal Accident...",blog,10/20/2013 21:09,0.0,"['cirrus', 'fatal', 'accidents', 'aircraft', '...",NaN,Cirrus fatal accidents drop more than GA or Am...,27.0,1
18,18,NaN,rick beach,1.0,"In December of 2005, the first post with the p...",blog,8/14/2013 17:46,0.0,"['caps', 'pull', 'altitude', 'early', 'control...",NaN,"Another exposition on the mantra Pull Early, P...",27.0,1
19,19,NaN,rick beach,0.0,"Quite often after an accident in a Cirrus, avi...",blog,7/20/2013 13:08,0.0,"['cirrus', 'experience', 'pilots', 'time', 'ac...",NaN,Update on pilot experience in Cirrus fatal acc...,27.0,1
20,20,NaN,rick beach,0.0,The Cirrus community reached a significant saf...,blog,7/11/2013 16:46,0.0,"['accidents', 'caps', 'fatal', 'cirrus', 'save...",NaN,Cirrus Safety Milestone: Equal number of CAPS ...,27.0,1
21,21,NaN,rick beach,0.0,What do we learn from recorded data in our Cir...,blog,6/16/2013 23:56,0.0,"['data', 'flight', 'cirrus', 'files', 'acciden...",NaN,Recorded flight data helps us fly more safely,27.0,1
22,22,NaN,rick beach,0.0,"Recently, two things coincided to bracket the ...",blog,5/25/2013 18:34,0.0,"['cirrus', 'safety', 'pilots', 'better', 'caps...",NaN,Another discussion of the Cirrus safety record,27.0,1
23,23,NaN,rick beach,1.0,"Today, I was invited to submit comments on a f...",blog,4/4/2013 2:14,0.0,"['accident', 'ntsb', 'factual', 'copa', 'safet...",NaN,Letter to NTSB concerning early access to fact...,27.0,1
24,24,NaN,rick beach,0.0,COPA\r\nSafety: Pull Often!\nby Rick Beach\n??...,blog,3/13/2013 22:29,0.0,"['plane', 'parachute', 'caps', 'copa', 'bob', ...",NaN,COPA Safety: Pull Often! (from COPA Pilot maga...,27.0,1
25,25,NaN,rick beach,2.0,"In the past few months, COPA has worked with C...",blog,12/9/2012 0:07,0.0,"['time', 'aircraft', 'cirrus', 'hours', 'data'...",NaN,Recalibrating the flying hours for the Cirrus ...,27.0,1
26,26,NaN,rick beach,2.0,Compare the past six months\r\nwith the same t...,blog,12/8/2012 11:03,0.0,"['caps', 'accidents', 'year', '2012', 'copa', ...",NaN,"In Last Six Months, Half the Fatal Accidents a...",27.0,1
27,27,NaN,rick beach,0.0,"In the accident history of Cirrus accidents, w...",blog,11/22/2012 19:25,0.0,"['caps', 'parachute', 'impact', 'ground', 'act...",NaN,Refining what we call a CAPS Save,27.0,1
28,28,NaN,rick beach,2.0,"In the thread, Cirrus fatal #89 in SR20 N764RV...",blog,7/16/2012 16:48,0.0,"['dissonance', 'cognitive', 'vfr', 'clouds', '...",NaN,On cognitive dissonance in flying,27.0,1
29,29,NaN,rick beach,1.0,Dr. Richard ?Â?Dick?Â? McGlaughlin and his d...,blog,1/10/2012 6:34,0.0,"['parachute', 'dick', 'plane', 'cirrus', 'wate...",NaN,Early Reflections on CAPS Pull #32 by Dick McG...,27.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,40,Service Center Spotlight,NaN,NaN,FAR WESTERN STATESCALIFORNIA American Aircraft...,magazine,NaN,NaN,"['aviation', 'pg', 'air', 'aircraft', 'aero', ...",NaN,NaN,0.0,3
71,41,Advertising Index,NaN,NaN,NEW YORK Boshart Enterprises Aircraft Services...,magazine,NaN,NaN,"['aviation', 'air', 'aircraft', 'pg', 'service...",NaN,NaN,0.0,3
72,42,President's Column,NaN,NaN,APRIL 20194 COPA PilotCOPA has the incredible ...,magazine,NaN,NaN,"['copa', 'com', 'members', 'event', 'pilot', '...",NaN,NaN,0.0,3
73,43,COPA News,NaN,NaN,APRIL 20196 COPA PilotSmall WorldAbout two yea...,magazine,NaN,NaN,"['copa', 'migration', 'new', 'cirrus', 'orlean...",NaN,NaN,0.0,3
74,44,Regional News,gil williamson,NaN,APRIL 201912 COPA PilotCOPA Pilot Can you give...,magazine,NaN,NaN,"['copa', 'pilot', 'plane', 'pilots', 'cirrus',...",NaN,NaN,24.0,3
75,45,Cirrus Perspective,NaN,NaN,APRIL 201918 COPA PilotI am also working on ex...,magazine,NaN,NaN,"['copa', 'foundation', 'pilot', 'board', 'memb...",NaN,NaN,0.0,3
76,46,Member Spotlight,kim blonigen,NaN,APRIL 201922 COPA PilotRegional and Internatio...,magazine,NaN,NaN,"['copa', 'events', 'international', 'migration...",NaN,NaN,23.0,3
77,47,Fly Africa ... Part Two,NaN,NaN,APRIL 201930 COPA PilotAIRCRAFT SALES PURCHASE...,magazine,NaN,NaN,"['copa', 'cirrus', 'year', 'pilot', 'csip', 'a...",NaN,NaN,0.0,3
78,48,Safety Talk,rick beach,NaN,APRIL 201940 COPA PilotVolume 14 Number 3COPA ...,magazine,NaN,NaN,"['copa', 'c2a', 'formation', 'pilot', 'pilots'...",NaN,NaN,27.0,3
79,49,Safety Feature,rick beach,NaN,APRIL 201944 COPA PilotElectronic Ignition sys...,magazine,NaN,NaN,"['engine', 'magneto', 'aircraft', 'electroair'...",NaN,NaN,27.0,3
80,50,Medical Musings,jerrold seckler,NaN,APRIL 201952 COPA Pilotnatural transition. Tho...,magazine,NaN,NaN,"['mission', 'pilot', 'lighthawk', 'make', 'new...",NaN,NaN,22.0,3
81,51,Training,trip taylor,NaN,APRIL 201954 COPA PilotI do if ll in the blank...,magazine,NaN,NaN,"['centerline', 'landing', 'pilot', 'pilots', '...",NaN,NaN,21.0,3
82,52,COPA Technical,NaN,NaN,APRIL 201958 COPA Pilotpilots tend to end up l...,magazine,NaN,NaN,"['aviation', 'aircraft', 'ad', 'pg', 'center',...",NaN,NaN,0.0,3
83,53,Directory of Authorized Service Centers,NaN,NaN,CIRRUS AUTHORIZED SERVICE CENTERSCIRRUS AUTHOR...,magazine,NaN,NaN,"['aviation', 'air', 'maintenance', 'service', ...",NaN,NaN,0.0,3
84,54,Service Center Spotlight,NaN,NaN,APRIL 201962 COPA PilotCIRRUS SERVICE CENTER S...,magazine,NaN,NaN,"['copa', 'join', '2830', '89130read', 'airplan...",NaN,NaN,0.0,3
85,55,Advertising Index,NaN,NaN,Volume 14 Number 3COPA Pilot 63Volume 14 Numbe...,magazine,NaN,NaN,"['14', '3copa', 'number', 'pilot', '63volume',...",NaN,NaN,0.0,3
86,56,President's Column,NaN,NaN,JULY AUGUST 20194 COPA PilotIts fullon summer ...,magazine,NaN,NaN,"['copa', 'members', 'com', 'event', 'great', '...",NaN,NaN,0.0,3
87,57,COPA News,NaN,NaN,JULY AUGUST 20196 COPA PilotREGIONALINTERNATIO...,magazine,NaN,NaN,"['trip', 'ight', 'copa', 'maya', 'adventure', ...",NaN,NaN,0.0,3
88,58,Regional News,gil williamson,NaN,JULY AUGUST 201912 COPA Pilothelped us tie dow...,magazine,NaN,NaN,"['copa', 'great', 'cirrus', 'mayan', 'campeche...",NaN,NaN,24.0,3
89,59,Cirrus Perspective,NaN,NaN,JULY AUGUST 201918 COPA Pilotexecutive ofcer C...,magazine,NaN,NaN,"['copa', 'pilot', 'brazil', 'cirrus', 'lohmann...",NaN,NaN,0.0,3
90,60,Member Spotlight,kim blonigen,NaN,JULY AUGUST 201922 COPA Pilottopics discussed ...,magazine,NaN,NaN,"['aircraft', 'copa', 'brazil', 'atc', 'policy'...",NaN,NaN,23.0,3
91,61,Fly Africa ... Part Two,NaN,NaN,JULY AUGUST 201930 COPA PilotHowever insurers ...,magazine,NaN,NaN,"['aircraft', 'insurance', 'coverage', 'damage'...",NaN,NaN,0.0,3
92,62,Safety Talk,rick beach,NaN,JULY AUGUST 201940 COPA Pilotcoastline where y...,magazine,NaN,NaN,"['mdi', 'bar', 'harbor', 'rst', 'park', 'acadi...",NaN,NaN,27.0,3
93,63,Safety Feature,rick beach,NaN,JULY AUGUST 201944 COPA Pilotcrossing the beac...,magazine,NaN,NaN,"['weather', 'cirrus', 'conditions', 'vfr', 'pi...",NaN,NaN,27.0,3
94,64,Medical Musings,jerrold seckler,NaN,JULY AUGUST 201952 COPA PilotFly with more ter...,magazine,NaN,NaN,"['weather', 'know', 'time', 'avoid', 'caps', '...",NaN,NaN,22.0,3
95,65,Training,trip taylor,NaN,JULY AUGUST 201954 COPA PilotSummer is here an...,magazine,NaN,NaN,"['night', 'guy', 'landings', 'currency', 'airc...",NaN,NaN,21.0,3
96,66,COPA Technical,NaN,NaN,JULY AUGUST 201958 COPA PilotThe ITGCKMBPC Int...,magazine,NaN,NaN,"['approach', 'cirrus', 'guy', 'landing', 'knot...",NaN,NaN,0.0,3
97,67,Directory of Authorized Service Centers,NaN,NaN,Volume 14 Number 6COPA Pilot 61Volume 14 Numbe...,magazine,NaN,NaN,"['14', '6copa', 'number', 'pilot', '61volume',...",NaN,NaN,0.0,3
98,68,Service Center Spotlight,NaN,NaN,JULY AUGUST 201962 COPA Pilotto maintain cours...,magazine,NaN,NaN,"['approach', 'cirrus', 'aircraft', 'pilots', '...",NaN,NaN,0.0,3
99,69,Advertising Index,NaN,NaN,Volume 14 Number 6COPA Pilot 635 percent incre...,magazine,NaN,NaN,"['aircraft', 'approach', 'pilots', 'pilot', 'a...",NaN,NaN,0.0,3

In [27]:
#Transform NaN in 'Like' column to 0.
for i in range(len(result)):
    if (np.isnan(result['Like'][i])):
        result['Like'][i] = 0

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [28]:
result.head(100)

,Unnamed: 0,Article,Author,Comment,Content,Data_source,Date,Like,Most_common_words,Table of Contents,Title,author_score,datasource_score
0,0,NaN,rick beach,0.0,"by RICK BEACH, COPA?? SAFETY CHAIR\nThis unusu...",blog,12/30/2018 23:52,4.0,"['caps', 'pilot', 'accident', 'rocket', 'deplo...",How did the accident unfold?What evidence was ...,"CAPS Deployment Anomaly at Colorado Springs, C...",27.0,1
1,1,NaN,rick beach,8.0,Every Cirrus aircraft built has a parachute sy...,blog,1/17/2016 0:50,0.0,"['caps', 'low', 'altitude', 'pull', 'attitude'...",How Low?How High?Know your Aircraft: The G5 is...,CAPS: How Low Can You Go? Or How High Do You N...,27.0,1
2,2,NaN,rick beach,2.0,(This article appears as the safety column in ...,blog,9/13/2017 23:27,1.0,"['cirrus', 'training', 'new', 'transition', 't...",Reach the Unreachable Low time-in-type vs low ...,"""Reach the Unreachable"" safety column in COPA ...",27.0,1
3,3,NaN,rick beach,0.0,This column will appear in the Nov/Dec 2018 is...,blog,10/15/2018 4:22,12.0,"['runway', 'figure', 'left', 'airplane', 'wing...",NaN,?Â?That Sounds Expensive?Â? -- It Happened t...,27.0,1
4,4,NaN,rick beach,4.0,A Note from the Guest Editor\nThis June 2017 i...,blog,6/10/2017 18:11,0.0,"['copa', 'training', 'cirrus', 'safety', 'pilo...",A Note from the Guest Editor Success has Many ...,Guest Editor column to Special Safety Issue of...,27.0,1
5,5,NaN,rick beach,0.0,CaresCritical Incident Response ProgramCIRP i...,blog,8/27/2019 23:15,0.0,"['cirp', 'copa', 'community', 'peer', 'support...",Critical Incident Response for the COPA Commun...,Critical Incident Response for the COPA Community,27.0,1
6,6,NaN,rick beach,5.0,"For??years,??safety??advocates??have??preached...",blog,1/17/2016 0:51,4.0,"['loss', 'control', 'accidents', 'flight', 'ci...",Cirrus Aircraft Studied Loss of ControlAnalysi...,COPA/Cirrus Aircraft Examine Loss of Control A...,27.0,1
7,7,NaN,rick beach,0.0,Having participated in several annual meetings...,blog,12/1/2015 18:52,1.0,"['ntsb', 'type', 'investigation', 'investigati...",NaN,Ways that Aviation Type Clubs can prepare and ...,27.0,1
8,8,NaN,rick beach,2.0,Compare the past six months\r\nwith the same t...,blog,12/8/2012 11:03,0.0,"['caps', 'accidents', 'year', '2012', 'copa', ...",NaN,"In Last Six Months, Half the Fatal Accidents a...",27.0,1
9,9,NaN,rick beach,5.0,In a recent discussion of the survivable CAPS ...,blog,11/30/2014 18:26,3.0,"['engine', 'fuel', 'oil', 'caps', 'power', 'co...",Recent Fatal Accidents BAD WEATHER FLYINGPILOT...,Turning Fatals into CAPS Saves and Avoiding CA...,27.0,1
10,10,NaN,rick beach,2.0,(updated with additional Probable Cause determ...,blog,11/24/2014 19:47,0.0,"['engine', 'loss', 'power', 'io', 'sr22', '550...",NaN,Reviewing the causes of loss of engine power i...,27.0,1
11,11,NaN,rick beach,2.0,"During the COPA dinner at Oshkosh 2014, a brie...",blog,8/21/2014 20:49,2.0,"['cirrus', 'accidents', 'fatal', 'aircraft', '...",NaN,Safety Good News presentation at COPA Dinner @...,27.0,1
12,12,NaN,rick beach,3.0,"Since the beginning of 2014, Cirrus accident r...",blog,7/1/2014 17:02,3.0,"['cirrus', 'accidents', 'fatal', 'flying', 'fl...",Fatalities in Cirrus AccidentsFatal Cirrus Acc...,Mid-Year 2014 Update on Improved Cirrus accide...,27.0,1
13,13,NaN,rick beach,0.0,"Recently, a forum discussion on BeechTalk posi...",blog,6/18/2014 20:52,0.0,"['pilot', 'caps', 'water', 'landed', 'engine',...",NaN,On CAPS deployments that landed in water -- ab...,27.0,1
14,14,NaN,rick beach,8.0,"Recently, a private conversation with a COPA m...",blog,6/18/2014 21:33,4.0,"['injuries', 'caps', 'fracture', 'lower', 'par...",NaN,On injuries from surviving a CAPS pull,27.0,1
15,15,NaN,rick beach,9.0,The Cirrus Owners and Pilots Association (COPA...,blog,4/1/2014 20:44,3.0,"['accidents', 'number', 'cirrus', 'fatal', 'ca...",Cirrus Fatal AccidentsFatalities in Cirrus Fat...,Cirrus accident history continues improvement ...,27.0,1
16,16,NaN,rick beach,2.0,As COPA members may know from frequenting the ...,blog,3/31/2014 19:08,0.0,"['accidents', 'maneuvering', 'cirrus', 'fatal'...",NTSB data on maneuvering in fatal accidentsMor...,About Maneuvering in Fatal Cirrus Accidents,27.0,1
17,17,NaN,rick beach,0.0,"A story from EAA,??Experimental Fatal Accident...",blog,10/20/2013 21:09,0.0,"['cirrus', 'fatal', 'accidents', 'aircraft', '...",NaN,Cirrus fatal accidents drop more than GA or Am...,27.0,1
18,18,NaN,rick beach,1.0,"In December of 2005, the first post with the p...",blog,8/14/2013 17:46,0.0,"['caps', 'pull', 'altitude', 'early', 'control...",NaN,"Another exposition on the mantra Pull Early, P...",27.0,1
19,19,NaN,rick beach,0.0,"Quite often after an accident in a Cirrus, avi...",blog,7/20/2013 13:08,0.0,"['cirrus', 'experience', 'pilots', 'time', 'ac...",NaN,Update on pilot experience in Cirrus fatal acc...,27.0,1
20,20,NaN,rick beach,0.0,The Cirrus community reached a significant saf...,blog,7/11/2013 16:46,0.0,"['accidents', 'caps', 'fatal', 'cirrus', 'save...",NaN,Cirrus Safety Milestone: Equal number of CAPS ...,27.0,1
21,21,NaN,rick beach,0.0,What do we learn from recorded data in our Cir...,blog,6/16/2013 23:56,0.0,"['data', 'flight', 'cirrus', 'files', 'acciden...",NaN,Recorded flight data helps us fly more safely,27.0,1
22,22,NaN,rick beach,0.0,"Recently, two things coincided to bracket the ...",blog,5/25/2013 18:34,0.0,"['cirrus', 'safety', 'pilots', 'better', 'caps...",NaN,Another discussion of the Cirrus safety record,27.0,1
23,23,NaN,rick beach,1.0,"Today, I was invited to submit comments on a f...",blog,4/4/2013 2:14,0.0,"['accident', 'ntsb', 'factual', 'copa', 'safet...",NaN,Letter to NTSB concerning early access to fact...,27.0,1
24,24,NaN,rick beach,0.0,COPA\r\nSafety: Pull Often!\nby Rick Beach\n??...,blog,3/13/2013 22:29,0.0,"['plane', 'parachute', 'caps', 'copa', 'bob', ...",NaN,COPA Safety: Pull Often! (from COPA Pilot maga...,27.0,1
25,25,NaN,rick beach,2.0,"In the past few months, COPA has worked with C...",blog,12/9/2012 0:07,0.0,"['time', 'aircraft', 'cirrus', 'hours', 'data'...",NaN,Recalibrating the flying hours for the Cirrus ...,27.0,1
26,26,NaN,rick beach,2.0,Compare the past six months\r\nwith the same t...,blog,12/8/2012 11:03,0.0,"['caps', 'accidents', 'year', '2012', 'copa', ...",NaN,"In Last Six Months, Half the Fatal Accidents a...",27.0,1
27,27,NaN,rick beach,0.0,"In the accident history of Cirrus accidents, w...",blog,11/22/2012 19:25,0.0,"['caps', 'parachute', 'impact', 'ground', 'act...",NaN,Refining what we call a CAPS Save,27.0,1
28,28,NaN,rick beach,2.0,"In the thread, Cirrus fatal #89 in SR20 N764RV...",blog,7/16/2012 16:48,0.0,"['dissonance', 'cognitive', 'vfr', 'clouds', '...",NaN,On cognitive dissonance in flying,27.0,1
29,29,NaN,rick beach,1.0,Dr. Richard ?Â?Dick?Â? McGlaughlin and his d...,blog,1/10/2012 6:34,0.0,"['parachute', 'dick', 'plane', 'cirrus', 'wate...",NaN,Early Reflections on CAPS Pull #32 by Dick McG...,27.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,40,Service Center Spotlight,NaN,NaN,FAR WESTERN STATESCALIFORNIA American Aircraft...,magazine,NaN,0.0,"['aviation', 'pg', 'air', 'aircraft', 'aero', ...",NaN,NaN,0.0,3
71,41,Advertising Index,NaN,NaN,NEW YORK Boshart Enterprises Aircraft Services...,magazine,NaN,0.0,"['aviation', 'air', 'aircraft', 'pg', 'service...",NaN,NaN,0.0,3
72,42,President's Column,NaN,NaN,APRIL 20194 COPA PilotCOPA has the incredible ...,magazine,NaN,0.0,"['copa', 'com', 'members', 'event', 'pilot', '...",NaN,NaN,0.0,3
73,43,COPA News,NaN,NaN,APRIL 20196 COPA PilotSmall WorldAbout two yea...,magazine,NaN,0.0,"['copa', 'migration', 'new', 'cirrus', 'orlean...",NaN,NaN,0.0,3
74,44,Regional News,gil williamson,NaN,APRIL 201912 COPA PilotCOPA Pilot Can you give...,magazine,NaN,0.0,"['copa', 'pilot', 'plane', 'pilots', 'cirrus',...",NaN,NaN,24.0,3
75,45,Cirrus Perspective,NaN,NaN,APRIL 201918 COPA PilotI am also working on ex...,magazine,NaN,0.0,"['copa', 'foundation', 'pilot', 'board', 'memb...",NaN,NaN,0.0,3
76,46,Member Spotlight,kim blonigen,NaN,APRIL 201922 COPA PilotRegional and Internatio...,magazine,NaN,0.0,"['copa', 'events', 'international', 'migration...",NaN,NaN,23.0,3
77,47,Fly Africa ... Part Two,NaN,NaN,APRIL 201930 COPA PilotAIRCRAFT SALES PURCHASE...,magazine,NaN,0.0,"['copa', 'cirrus', 'year', 'pilot', 'csip', 'a...",NaN,NaN,0.0,3
78,48,Safety Talk,rick beach,NaN,APRIL 201940 COPA PilotVolume 14 Number 3COPA ...,magazine,NaN,0.0,"['copa', 'c2a', 'formation', 'pilot', 'pilots'...",NaN,NaN,27.0,3
79,49,Safety Feature,rick beach,NaN,APRIL 201944 COPA PilotElectronic Ignition sys...,magazine,NaN,0.0,"['engine', 'magneto', 'aircraft', 'electroair'...",NaN,NaN,27.0,3
80,50,Medical Musings,jerrold seckler,NaN,APRIL 201952 COPA Pilotnatural transition. Tho...,magazine,NaN,0.0,"['mission', 'pilot', 'lighthawk', 'make', 'new...",NaN,NaN,22.0,3
81,51,Training,trip taylor,NaN,APRIL 201954 COPA PilotI do if ll in the blank...,magazine,NaN,0.0,"['centerline', 'landing', 'pilot', 'pilots', '...",NaN,NaN,21.0,3
82,52,COPA Technical,NaN,NaN,APRIL 201958 COPA Pilotpilots tend to end up l...,magazine,NaN,0.0,"['aviation', 'aircraft', 'ad', 'pg', 'center',...",NaN,NaN,0.0,3
83,53,Directory of Authorized Service Centers,NaN,NaN,CIRRUS AUTHORIZED SERVICE CENTERSCIRRUS AUTHOR...,magazine,NaN,0.0,"['aviation', 'air', 'maintenance', 'service', ...",NaN,NaN,0.0,3
84,54,Service Center Spotlight,NaN,NaN,APRIL 201962 COPA PilotCIRRUS SERVICE CENTER S...,magazine,NaN,0.0,"['copa', 'join', '2830', '89130read', 'airplan...",NaN,NaN,0.0,3
85,55,Advertising Index,NaN,NaN,Volume 14 Number 3COPA Pilot 63Volume 14 Numbe...,magazine,NaN,0.0,"['14', '3copa', 'number', 'pilot', '63volume',...",NaN,NaN,0.0,3
86,56,President's Column,NaN,NaN,JULY AUGUST 20194 COPA PilotIts fullon summer ...,magazine,NaN,0.0,"['copa', 'members', 'com', 'event', 'great', '...",NaN,NaN,0.0,3
87,57,COPA News,NaN,NaN,JULY AUGUST 20196 COPA PilotREGIONALINTERNATIO...,magazine,NaN,0.0,"['trip', 'ight', 'copa', 'maya', 'adventure', ...",NaN,NaN,0.0,3
88,58,Regional News,gil williamson,NaN,JULY AUGUST 201912 COPA Pilothelped us tie dow...,magazine,NaN,0.0,"['copa', 'great', 'cirrus', 'mayan', 'campeche...",NaN,NaN,24.0,3
89,59,Cirrus Perspective,NaN,NaN,JULY AUGUST 201918 COPA Pilotexecutive ofcer C...,magazine,NaN,0.0,"['copa', 'pilot', 'brazil', 'cirrus', 'lohmann...",NaN,NaN,0.0,3
90,60,Member Spotlight,kim blonigen,NaN,JULY AUGUST 201922 COPA Pilottopics discussed ...,magazine,NaN,0.0,"['aircraft', 'copa', 'brazil', 'atc', 'policy'...",NaN,NaN,23.0,3
91,61,Fly Africa ... Part Two,NaN,NaN,JULY AUGUST 201930 COPA PilotHowever insurers ...,magazine,NaN,0.0,"['aircraft', 'insurance', 'coverage', 'damage'...",NaN,NaN,0.0,3
92,62,Safety Talk,rick beach,NaN,JULY AUGUST 201940 COPA Pilotcoastline where y...,magazine,NaN,0.0,"['mdi', 'bar', 'harbor', 'rst', 'park', 'acadi...",NaN,NaN,27.0,3
93,63,Safety Feature,rick beach,NaN,JULY AUGUST 201944 COPA Pilotcrossing the beac...,magazine,NaN,0.0,"['weather', 'cirrus', 'conditions', 'vfr', 'pi...",NaN,NaN,27.0,3
94,64,Medical Musings,jerrold seckler,NaN,JULY AUGUST 201952 COPA PilotFly with more ter...,magazine,NaN,0.0,"['weather', 'know', 'time', 'avoid', 'caps', '...",NaN,NaN,22.0,3
95,65,Training,trip taylor,NaN,JULY AUGUST 201954 COPA PilotSummer is here an...,magazine,NaN,0.0,"['night', 'guy', 'landings', 'currency', 'airc...",NaN,NaN,21.0,3
96,66,COPA Technical,NaN,NaN,JULY AUGUST 201958 COPA PilotThe ITGCKMBPC Int...,magazine,NaN,0.0,"['approach', 'cirrus', 'guy', 'landing', 'knot...",NaN,NaN,0.0,3
97,67,Directory of Authorized Service Centers,NaN,NaN,Volume 14 Number 6COPA Pilot 61Volume 14 Numbe...,magazine,NaN,0.0,"['14', '6copa', 'number', 'pilot', '61volume',...",NaN,NaN,0.0,3
98,68,Service Center Spotlight,NaN,NaN,JULY AUGUST 201962 COPA Pilotto maintain cours...,magazine,NaN,0.0,"['approach', 'cirrus', 'aircraft', 'pilots', '...",NaN,NaN,0.0,3
99,69,Advertising Index,NaN,NaN,Volume 14 Number 6COPA Pilot 635 percent incre...,magazine,NaN,0.0,"['aircraft', 'approach', 'pilots', 'pilot', 'a...",NaN,NaN,0.0,3

In [29]:
#Transform NaN in 'Comment' column to 0.
for i in range(len(result)):
    if (np.isnan(result['Comment'][i])):
        result['Comment'][i] = 0

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [30]:
result['like_score'] = result['Like']
result['comment_score'] = result['Comment']

In [31]:
result.head(100)

,Unnamed: 0,Article,Author,Comment,Content,Data_source,Date,Like,Most_common_words,Table of Contents,Title,author_score,datasource_score,like_score,comment_score
0,0,NaN,rick beach,0.0,"by RICK BEACH, COPA?? SAFETY CHAIR\nThis unusu...",blog,12/30/2018 23:52,4.0,"['caps', 'pilot', 'accident', 'rocket', 'deplo...",How did the accident unfold?What evidence was ...,"CAPS Deployment Anomaly at Colorado Springs, C...",27.0,1,4.0,0.0
1,1,NaN,rick beach,8.0,Every Cirrus aircraft built has a parachute sy...,blog,1/17/2016 0:50,0.0,"['caps', 'low', 'altitude', 'pull', 'attitude'...",How Low?How High?Know your Aircraft: The G5 is...,CAPS: How Low Can You Go? Or How High Do You N...,27.0,1,0.0,8.0
2,2,NaN,rick beach,2.0,(This article appears as the safety column in ...,blog,9/13/2017 23:27,1.0,"['cirrus', 'training', 'new', 'transition', 't...",Reach the Unreachable Low time-in-type vs low ...,"""Reach the Unreachable"" safety column in COPA ...",27.0,1,1.0,2.0
3,3,NaN,rick beach,0.0,This column will appear in the Nov/Dec 2018 is...,blog,10/15/2018 4:22,12.0,"['runway', 'figure', 'left', 'airplane', 'wing...",NaN,?Â?That Sounds Expensive?Â? -- It Happened t...,27.0,1,12.0,0.0
4,4,NaN,rick beach,4.0,A Note from the Guest Editor\nThis June 2017 i...,blog,6/10/2017 18:11,0.0,"['copa', 'training', 'cirrus', 'safety', 'pilo...",A Note from the Guest Editor Success has Many ...,Guest Editor column to Special Safety Issue of...,27.0,1,0.0,4.0
5,5,NaN,rick beach,0.0,CaresCritical Incident Response ProgramCIRP i...,blog,8/27/2019 23:15,0.0,"['cirp', 'copa', 'community', 'peer', 'support...",Critical Incident Response for the COPA Commun...,Critical Incident Response for the COPA Community,27.0,1,0.0,0.0
6,6,NaN,rick beach,5.0,"For??years,??safety??advocates??have??preached...",blog,1/17/2016 0:51,4.0,"['loss', 'control', 'accidents', 'flight', 'ci...",Cirrus Aircraft Studied Loss of ControlAnalysi...,COPA/Cirrus Aircraft Examine Loss of Control A...,27.0,1,4.0,5.0
7,7,NaN,rick beach,0.0,Having participated in several annual meetings...,blog,12/1/2015 18:52,1.0,"['ntsb', 'type', 'investigation', 'investigati...",NaN,Ways that Aviation Type Clubs can prepare and ...,27.0,1,1.0,0.0
8,8,NaN,rick beach,2.0,Compare the past six months\r\nwith the same t...,blog,12/8/2012 11:03,0.0,"['caps', 'accidents', 'year', '2012', 'copa', ...",NaN,"In Last Six Months, Half the Fatal Accidents a...",27.0,1,0.0,2.0
9,9,NaN,rick beach,5.0,In a recent discussion of the survivable CAPS ...,blog,11/30/2014 18:26,3.0,"['engine', 'fuel', 'oil', 'caps', 'power', 'co...",Recent Fatal Accidents BAD WEATHER FLYINGPILOT...,Turning Fatals into CAPS Saves and Avoiding CA...,27.0,1,3.0,5.0
10,10,NaN,rick beach,2.0,(updated with additional Probable Cause determ...,blog,11/24/2014 19:47,0.0,"['engine', 'loss', 'power', 'io', 'sr22', '550...",NaN,Reviewing the causes of loss of engine power i...,27.0,1,0.0,2.0
11,11,NaN,rick beach,2.0,"During the COPA dinner at Oshkosh 2014, a brie...",blog,8/21/2014 20:49,2.0,"['cirrus', 'accidents', 'fatal', 'aircraft', '...",NaN,Safety Good News presentation at COPA Dinner @...,27.0,1,2.0,2.0
12,12,NaN,rick beach,3.0,"Since the beginning of 2014, Cirrus accident r...",blog,7/1/2014 17:02,3.0,"['cirrus', 'accidents', 'fatal', 'flying', 'fl...",Fatalities in Cirrus AccidentsFatal Cirrus Acc...,Mid-Year 2014 Update on Improved Cirrus accide...,27.0,1,3.0,3.0
13,13,NaN,rick beach,0.0,"Recently, a forum discussion on BeechTalk posi...",blog,6/18/2014 20:52,0.0,"['pilot', 'caps', 'water', 'landed', 'engine',...",NaN,On CAPS deployments that landed in water -- ab...,27.0,1,0.0,0.0
14,14,NaN,rick beach,8.0,"Recently, a private conversation with a COPA m...",blog,6/18/2014 21:33,4.0,"['injuries', 'caps', 'fracture', 'lower', 'par...",NaN,On injuries from surviving a CAPS pull,27.0,1,4.0,8.0
15,15,NaN,rick beach,9.0,The Cirrus Owners and Pilots Association (COPA...,blog,4/1/2014 20:44,3.0,"['accidents', 'number', 'cirrus', 'fatal', 'ca...",Cirrus Fatal AccidentsFatalities in Cirrus Fat...,Cirrus accident history continues improvement ...,27.0,1,3.0,9.0
16,16,NaN,rick beach,2.0,As COPA members may know from frequenting the ...,blog,3/31/2014 19:08,0.0,"['accidents', 'maneuvering', 'cirrus', 'fatal'...",NTSB data on maneuvering in fatal accidentsMor...,About Maneuvering in Fatal Cirrus Accidents,27.0,1,0.0,2.0
17,17,NaN,rick beach,0.0,"A story from EAA,??Experimental Fatal Accident...",blog,10/20/2013 21:09,0.0,"['cirrus', 'fatal', 'accidents', 'aircraft', '...",NaN,Cirrus fatal accidents drop more than GA or Am...,27.0,1,0.0,0.0
18,18,NaN,rick beach,1.0,"In December of 2005, the first post with the p...",blog,8/14/2013 17:46,0.0,"['caps', 'pull', 'altitude', 'early', 'control...",NaN,"Another exposition on the mantra Pull Early, P...",27.0,1,0.0,1.0
19,19,NaN,rick beach,0.0,"Quite often after an accident in a Cirrus, avi...",blog,7/20/2013 13:08,0.0,"['cirrus', 'experience', 'pilots', 'time', 'ac...",NaN,Update on pilot experience in Cirrus fatal acc...,27.0,1,0.0,0.0
20,20,NaN,rick beach,0.0,The Cirrus community reached a significant saf...,blog,7/11/2013 16:46,0.0,"['accidents', 'caps', 'fatal', 'cirrus', 'save...",NaN,Cirrus Safety Milestone: Equal number of CAPS ...,27.0,1,0.0,0.0
21,21,NaN,rick beach,0.0,What do we learn from recorded data in our Cir...,blog,6/16/2013 23:56,0.0,"['data', 'flight', 'cirrus', 'files', 'acciden...",NaN,Recorded flight data helps us fly more safely,27.0,1,0.0,0.0
22,22,NaN,rick beach,0.0,"Recently, two things coincided to bracket the ...",blog,5/25/2013 18:34,0.0,"['cirrus', 'safety', 'pilots', 'better', 'caps...",NaN,Another discussion of the Cirrus safety record,27.0,1,0.0,0.0
23,23,NaN,rick beach,1.0,"Today, I was invited to submit comments on a f...",blog,4/4/2013 2:14,0.0,"['accident', 'ntsb', 'factual', 'copa', 'safet...",NaN,Letter to NTSB concerning early access to fact...,27.0,1,0.0,1.0
24,24,NaN,rick beach,0.0,COPA\r\nSafety: Pull Often!\nby Rick Beach\n??...,blog,3/13/2013 22:29,0.0,"['plane', 'parachute', 'caps', 'copa', 'bob', ...",NaN,COPA Safety: Pull Often! (from COPA Pilot maga...,27.0,1,0.0,0.0
25,25,NaN,rick beach,2.0,"In the past few months, COPA has worked with C...",blog,12/9/2012 0:07,0.0,"['time', 'aircraft', 'cirrus', 'hours', 'data'...",NaN,Recalibrating the flying hours for the Cirrus ...,27.0,1,0.0,2.0
26,26,NaN,rick beach,2.0,Compare the past six months\r\nwith the same t...,blog,12/8/2012 11:03,0.0,"['caps', 'accidents', 'year', '2012', 'copa', ...",NaN,"In Last Six Months, Half the Fatal Accidents a...",27.0,1,0.0,2.0
27,27,NaN,rick beach,0.0,"In the accident history of Cirrus accidents, w...",blog,11/22/2012 19:25,0.0,"['caps', 'parachute', 'impact', 'ground', 'act...",NaN,Refining what we call a CAPS Save,27.0,1,0.0,0.0
28,28,NaN,rick beach,2.0,"In the thread, Cirrus fatal #89 in SR20 N764RV...",blog,7/16/2012 16:48,0.0,"['dissonance', 'cognitive', 'vfr', 'clouds', '...",NaN,On cognitive dissonance in flying,27.0,1,0.0,2.0
29,29,NaN,rick beach,1.0,Dr. Richard ?Â?Dick?Â? McGlaughlin and his d...,blog,1/10/2012 6:34,0.0,"['parachute', 'dick', 'plane', 'cirrus', 'wate...",NaN,Early Reflections on CAPS Pull #32 by Dick McG...,27.0,1,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,40,Service Center Spotlight,NaN,0.0,FAR WESTERN STATESCALIFORNIA American Aircraft...,magazine,NaN,0.0,"['aviation', 'pg', 'air', 'aircraft', 'aero', ...",NaN,NaN,0.0,3,0.0,0.0
71,41,Advertising Index,NaN,0.0,NEW YORK Boshart Enterprises Aircraft Services...,magazine,NaN,0.0,"['aviation', 'air', 'aircraft', 'pg', 'service...",NaN,NaN,0.0,3,0.0,0.0
72,42,President's Column,NaN,0.0,APRIL 20194 COPA PilotCOPA has the incredible ...,magazine,NaN,0.0,"['copa', 'com', 'members', 'event', 'pilot', '...",NaN,NaN,0.0,3,0.0,0.0
73,43,COPA News,NaN,0.0,APRIL 20196 COPA PilotSmall WorldAbout two yea...,magazine,NaN,0.0,"['copa', 'migration', 'new', 'cirrus', 'orlean...",NaN,NaN,0.0,3,0.0,0.0
74,44,Regional News,gil williamson,0.0,APRIL 201912 COPA PilotCOPA Pilot Can you give...,magazine,NaN,0.0,"['copa', 'pilot', 'plane', 'pilots', 'cirrus',...",NaN,NaN,24.0,3,0.0,0.0
75,45,Cirrus Perspective,NaN,0.0,APRIL 201918 COPA PilotI am also working on ex...,magazine,NaN,0.0,"['copa', 'foundation', 'pilot', 'board', 'memb...",NaN,NaN,0.0,3,0.0,0.0
76,46,Member Spotlight,kim blonigen,0.0,APRIL 201922 COPA PilotRegional and Internatio...,magazine,NaN,0.0,"['copa', 'events', 'international', 'migration...",NaN,NaN,23.0,3,0.0,0.0
77,47,Fly Africa ... Part Two,NaN,0.0,APRIL 201930 COPA PilotAIRCRAFT SALES PURCHASE...,magazine,NaN,0.0,"['copa', 'cirrus', 'year', 'pilot', 'csip', 'a...",NaN,NaN,0.0,3,0.0,0.0
78,48,Safety Talk,rick beach,0.0,APRIL 201940 COPA PilotVolume 14 Number 3COPA ...,magazine,NaN,0.0,"['copa', 'c2a', 'formation', 'pilot', 'pilots'...",NaN,NaN,27.0,3,0.0,0.0
79,49,Safety Feature,rick beach,0.0,APRIL 201944 COPA PilotElectronic Ignition sys...,magazine,NaN,0.0,"['engine', 'magneto', 'aircraft', 'electroair'...",NaN,NaN,27.0,3,0.0,0.0
80,50,Medical Musings,jerrold seckler,0.0,APRIL 201952 COPA Pilotnatural transition. Tho...,magazine,NaN,0.0,"['mission', 'pilot', 'lighthawk', 'make', 'new...",NaN,NaN,22.0,3,0.0,0.0
81,51,Training,trip taylor,0.0,APRIL 201954 COPA PilotI do if ll in the blank...,magazine,NaN,0.0,"['centerline', 'landing', 'pilot', 'pilots', '...",NaN,NaN,21.0,3,0.0,0.0
82,52,COPA Technical,NaN,0.0,APRIL 201958 COPA Pilotpilots tend to end up l...,magazine,NaN,0.0,"['aviation', 'aircraft', 'ad', 'pg', 'center',...",NaN,NaN,0.0,3,0.0,0.0
83,53,Directory of Authorized Service Centers,NaN,0.0,CIRRUS AUTHORIZED SERVICE CENTERSCIRRUS AUTHOR...,magazine,NaN,0.0,"['aviation', 'air', 'maintenance', 'service', ...",NaN,NaN,0.0,3,0.0,0.0
84,54,Service Center Spotlight,NaN,0.0,APRIL 201962 COPA PilotCIRRUS SERVICE CENTER S...,magazine,NaN,0.0,"['copa', 'join', '2830', '89130read', 'airplan...",NaN,NaN,0.0,3,0.0,0.0
85,55,Advertising Index,NaN,0.0,Volume 14 Number 3COPA Pilot 63Volume 14 Numbe...,magazine,NaN,0.0,"['14', '3copa', 'number', 'pilot', '63volume',...",NaN,NaN,0.0,3,0.0,0.0
86,56,President's Column,NaN,0.0,JULY AUGUST 20194 COPA PilotIts fullon summer ...,magazine,NaN,0.0,"['copa', 'members', 'com', 'event', 'great', '...",NaN,NaN,0.0,3,0.0,0.0
87,57,COPA News,NaN,0.0,JULY AUGUST 20196 COPA PilotREGIONALINTERNATIO...,magazine,NaN,0.0,"['trip', 'ight', 'copa', 'maya', 'adventure', ...",NaN,NaN,0.0,3,0.0,0.0
88,58,Regional News,gil williamson,0.0,JULY AUGUST 201912 COPA Pilothelped us tie dow...,magazine,NaN,0.0,"['copa', 'great', 'cirrus', 'mayan', 'campeche...",NaN,NaN,24.0,3,0.0,0.0
89,59,Cirrus Perspective,NaN,0.0,JULY AUGUST 201918 COPA Pilotexecutive ofcer C...,magazine,NaN,0.0,"['copa', 'pilot', 'brazil', 'cirrus', 'lohmann...",NaN,NaN,0.0,3,0.0,0.0
90,60,Member Spotlight,kim blonigen,0.0,JULY AUGUST 201922 COPA Pilottopics discussed ...,magazine,NaN,0.0,"['aircraft', 'copa', 'brazil', 'atc', 'policy'...",NaN,NaN,23.0,3,0.0,0.0
91,61,Fly Africa ... Part Two,NaN,0.0,JULY AUGUST 201930 COPA PilotHowever insurers ...,magazine,NaN,0.0,"['aircraft', 'insurance', 'coverage', 'damage'...",NaN,NaN,0.0,3,0.0,0.0
92,62,Safety Talk,rick beach,0.0,JULY AUGUST 201940 COPA Pilotcoastline where y...,magazine,NaN,0.0,"['mdi', 'bar', 'harbor', 'rst', 'park', 'acadi...",NaN,NaN,27.0,3,0.0,0.0
93,63,Safety Feature,rick beach,0.0,JULY AUGUST 201944 COPA Pilotcrossing the beac...,magazine,NaN,0.0,"['weather', 'cirrus', 'conditions', 'vfr', 'pi...",NaN,NaN,27.0,3,0.0,0.0
94,64,Medical Musings,jerrold seckler,0.0,JULY AUGUST 201952 COPA PilotFly with more ter...,magazine,NaN,0.0,"['weather', 'know', 'time', 'avoid', 'caps', '...",NaN,NaN,22.0,3,0.0,0.0
95,65,Training,trip taylor,0.0,JULY AUGUST 201954 COPA PilotSummer is here an...,magazine,NaN,0.0,"['night', 'guy', 'landings', 'currency', 'airc...",NaN,NaN,21.0,3,0.0,0.0
96,66,COPA Technical,NaN,0.0,JULY AUGUST 201958 COPA PilotThe ITGCKMBPC Int...,magazine,NaN,0.0,"['approach', 'cirrus', 'guy', 'landing', 'knot...",NaN,NaN,0.0,3,0.0,0.0
97,67,Directory of Authorized Service Centers,NaN,0.0,Volume 14 Number 6COPA Pilot 61Volume 14 Numbe...,magazine,NaN,0.0,"['14', '6copa', 'number', 'pilot', '61volume',...",NaN,NaN,0.0,3,0.0,0.0
98,68,Service Center Spotlight,NaN,0.0,JULY AUGUST 201962 COPA Pilotto maintain cours...,magazine,NaN,0.0,"['approach', 'cirrus', 'aircraft', 'pilots', '...",NaN,NaN,0.0,3,0.0,0.0
99,69,Advertising Index,NaN,0.0,Volume 14 Number 6COPA Pilot 635 percent incre...,magazine,NaN,0.0,"['aircraft', 'approach', 'pilots', 'pilot', 'a...",NaN,NaN,0.0,3,0.0,0.0

The result here is ready for user input. Once user input words match with Most_common_words, calculate the match score, then normalize and add up with author_score, datasource_score, like_score, and comment_score to get the final score for each row. Then rank the result according to the final total score to get the optimized putput.